[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gjenerator"
version = "1.0.0"
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.8"'
]