name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.7'
    - name: Install dependencies
      run: |
        python3 -m pip install --user pipx
        pipx ensurepath
        pipx install poetry
        poetry install
    - name: Analysing the code with pylint
      run: |
        poetry run pylint ./
